services:
 - type: web                 
   name: django-ci-app       
   runtime: python          
# Type de service 
# Nom de l'app 
# Environnement 
   buildCommand: "./build.sh"  # Commande de construction 
   startCommand: "gunicorn myproject.wsgi:application" # Commande de d√©marrage 
   